name: cicd flow
on: 
 push:
   branches:
     - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: build
      run: |
        sh "mvn clean package -DskipTests=true"
        archive 'target/*.jar